/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assigmentdammay;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Tu Anh
 */
public class ProductPanel extends javax.swing.JPanel {
Connection conn = null;
PreparedStatement pst = null;
ResultSet rs = null;
    /**
     * Creates new form ProductPanel
     */
    public ProductPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ListProduct = new javax.swing.JList<>();
        RefreshProduct = new javax.swing.JButton();
        AddProduct = new javax.swing.JButton();
        UpdateProduct = new javax.swing.JButton();
        DeleteProduct = new javax.swing.JButton();
        ProductName = new javax.swing.JTextField();
        Price = new javax.swing.JTextField();
        Image = new javax.swing.JTextField();
        SearchProduct = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        BrandId = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        ListProduct.setModel(new javax.swing.AbstractListModel<Product>() {
            Product[] strings = {new Product("1","1","1","1","1"),new Product("1","2","1","2","1")};
            public int getSize() { return strings.length; }
            public Product getElementAt(int i) { return strings[i]; }
        });
        ListProduct.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListProductValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ListProduct);

        RefreshProduct.setText("Refresh");
        RefreshProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshProductActionPerformed(evt);
            }
        });

        AddProduct.setText("Thêm");
        AddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProductActionPerformed(evt);
            }
        });

        UpdateProduct.setText("Sửa");
        UpdateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateProductActionPerformed(evt);
            }
        });

        DeleteProduct.setText("Xóa");
        DeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteProductActionPerformed(evt);
            }
        });

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        BrandId.setModel(new javax.swing.DefaultComboBoxModel<Brand>(new Brand[] { new Brand("1","1"),new Brand("2","2")}));
        BrandId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrandIdActionPerformed(evt);
            }
        });

        jLabel1.setText("Tên mặt hàng");

        jLabel2.setText("Đơn giá");

        jLabel3.setText("Link ảnh");

        jLabel4.setText("Thương hiệu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RefreshProduct)
                        .addGap(33, 33, 33)
                        .addComponent(SearchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(SearchButton)
                        .addGap(0, 45, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ProductName)
                                    .addComponent(Price)
                                    .addComponent(Image)
                                    .addComponent(BrandId, 0, 126, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddProduct)
                            .addComponent(UpdateProduct)
                            .addComponent(DeleteProduct))))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RefreshProduct)
                    .addComponent(SearchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddProduct)
                            .addComponent(jLabel1))
                        .addGap(9, 9, 9)
                        .addComponent(ProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(UpdateProduct)
                                .addGap(39, 39, 39)
                                .addComponent(DeleteProduct)
                                .addGap(30, 30, 30))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BrandId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RefreshProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshProductActionPerformed
        // TODO add your handling code here:
         dm.removeAllElements();
         dc.removeAllElements();
        addItemtoList();
        addItemtoComboBox();
       
    }//GEN-LAST:event_RefreshProductActionPerformed

    private void AddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProductActionPerformed
        // TODO add your handling code here:
           conn = MysqlConnect.connectDB();
            String sql = "INSERT INTO product (Product_Name,Price,Img,Brand_Id) VALUES (?,?,?,?)";
            try{
                pst = conn.prepareStatement(sql);
                pst.setString(1, ProductName.getText());
                pst.setString(2,Price.getText());
                 pst.setString(3,Image.getText());
                 Brand brand = (Brand)BrandId.getSelectedItem();
                 pst.setString(4,brand.getId());
                 

                int a =pst.executeUpdate();
                if(a>0){
                    JOptionPane.showMessageDialog(null, "Add Product Success");
                      dm.removeAllElements();
                     addItemtoList();
                }else{
                JOptionPane.showMessageDialog(null, "Add Product Failure");}
            }catch(Exception e){
              JOptionPane.showMessageDialog(null, "Co loi xay ra"+e);}
    }//GEN-LAST:event_AddProductActionPerformed

    private void BrandIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrandIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BrandIdActionPerformed

    private void UpdateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateProductActionPerformed
        // TODO add your handling code here:
          conn = MysqlConnect.connectDB();
            String sql = "UPDATE product SET Product_name =?, Price = ?, Img =?, Brand_Id =? WHERE Product_id =?";
            try{
                pst = conn.prepareStatement(sql);
                pst.setString(1, ProductName.getText());
                Product product = ListProduct.getSelectedValue();
                String id = product.getId();
                pst.setString(2,Price.getText());
                pst.setString(3,Image.getText());
                Brand brand = (Brand)BrandId.getSelectedItem();
                String brandId = brand.getId();
                pst.setString(4,brandId);
                pst.setString(5,id);
                int a =  pst.executeUpdate();
               if(a>0){
                                   JOptionPane.showMessageDialog(null, "Update Brand Success");
                                     dm.removeAllElements();
                                     addItemtoList();

               }else{
                                   JOptionPane.showMessageDialog(null, "Update Brand Failure");

               }
            }catch(Exception e){
             System.out.println("Co loi xay ra "+e);}
    }//GEN-LAST:event_UpdateProductActionPerformed

    private void ListProductValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListProductValueChanged
        // TODO add your handling code here:
        Product product = ListProduct.getSelectedValue();
        ProductName.setText(product.ProductName);
        Price.setText(product.Price);
        Image.setText(product.Image);
        
       
          conn = MysqlConnect.connectDB();
                String sql = "SELECT * FROM brand WHERE Brand_Id =?";       
             try{
                pst = conn.prepareStatement(sql);
               pst.setString(1,product.BrandId);
               
                 rs =  pst.executeQuery();
             while(rs.next()){
                  Brand br = new Brand(rs.getString("Brand_Id"),rs.getString("Brand_Name"));
                 
                  
                  
                  BrandId.setSelectedItem(br.toString());
                  

               }
            }catch(Exception e){
             System.out.println("Co loi xay ra "+e);}
        
    }//GEN-LAST:event_ListProductValueChanged

    private void DeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteProductActionPerformed
        // TODO add your handling code here:
        conn = MysqlConnect.connectDB();
            String sql = " DELETE FROM product WHERE Product_id =?";
            try{
                pst = conn.prepareStatement(sql);
               
                Product product = ListProduct.getSelectedValue();
                pst.setString(1,product.getId());
                int a =  pst.executeUpdate();
               if(a>0){
                                   JOptionPane.showMessageDialog(null, "Delete Product Success");
                                     dm.removeAllElements();
                                      addItemtoList();

               }else{
                                   JOptionPane.showMessageDialog(null, "Delete Product Failure");

               }
            }catch(Exception e){
            
              JOptionPane.showMessageDialog(null, "Delete Product Failure \n"+e);
            }
    }//GEN-LAST:event_DeleteProductActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
         conn = MysqlConnect.connectDB();
            String sql = "SELECT * FROM product WHERE Product_name =?";
            
            try{
                  String productName  = SearchProduct.getText();
             
                pst = conn.prepareStatement(sql);
                pst.setString(1,productName);
               
             
                rs =  pst.executeQuery();
               while(rs.next()){
                  Product pr = new Product(rs.getString("Product_id"),rs.getString("Product_name"),rs.getString("Price"),rs.getString("Img"),rs.getString("Brand_Id"));
                  dm.removeAllElements();
                add(pr);
               }
            }catch(Exception e){
             System.out.println("Co loi xay ra "+e);}
    }//GEN-LAST:event_SearchButtonActionPerformed

    public void addItemtoComboBox(){
    conn = MysqlConnect.connectDB();
            String sql = "SELECT * FROM brand";
            try{
                pst = conn.prepareStatement(sql);
               
                rs =  pst.executeQuery();
               while(rs.next()){
                  Brand br = new Brand(rs.getString("Brand_Id"),rs.getString("Brand_Name"));
                  addCombox(br);
               }
            }catch(Exception e){
             System.out.println("Co loi xay ra "+e);}
    }
     DefaultComboBoxModel<Brand> dc = new DefaultComboBoxModel();
private void addCombox(Brand br){
    BrandId.setModel(dc);
    
   dc.addElement(br);
    
}
private void addItemtoList(){
 conn = MysqlConnect.connectDB();
            String sql = "SELECT * FROM product";
            try{
                pst = conn.prepareStatement(sql);
               
                rs =  pst.executeQuery();
               while(rs.next()){
                  Product pr = new Product(rs.getString("Product_id"),rs.getString("Product_name"),rs.getString("Price"),rs.getString("Img"),rs.getString("Brand_Id"));
                  add(pr);
               }
            }catch(Exception e){
             System.out.println("Co loi xay ra "+e);}
}
 DefaultListModel<Product> dm = new DefaultListModel();
private void add(Product pr){
    ListProduct.setModel(dm);
    
    dm.addElement(pr);
    
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddProduct;
    private javax.swing.JComboBox<Brand> BrandId;
    private javax.swing.JButton DeleteProduct;
    private javax.swing.JTextField Image;
    private javax.swing.JList<Product> ListProduct;
    private javax.swing.JTextField Price;
    private javax.swing.JTextField ProductName;
    private javax.swing.JButton RefreshProduct;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SearchProduct;
    private javax.swing.JButton UpdateProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
